name: 'ecommerce_dw'
version: '1.0.0'
config-version: 2

profile: 'ecommerce'

model-paths: ["models"]
test-paths: ["tests"]
macro-paths: ["macros"]

models:
  ecommerce_dw:
    staging:
      +materialized: view
      +schema: staging
    intermediate:
      +materialized: ephemeral
    marts:
      +materialized: table
      +schema: marts