ecommerce:
  target: dev
  outputs:
    dev:
      type: postgres
      host: postgres
      user: airflow
      password: airflow
      post: 5432
      dbname: airflow
      schema: warehouse
      threads: 4